### ISSUE TITLE
please add some features

### ISSUE THREAD

**Issue by deeptube** [smfils1/youtube-clone#4]
Hi Samuel,
at the first special thanks for your special clone work ,
1-if its possible make remote upload feature for uploading videos
2-how to increase the limitation of upload video from 25mb ?
3-if its possible make "deploy to heroku" button on your repo to easily add buildpacks & other env variables on deploy section of dyno.
4- if its possible made golive with pre-record clip & can use rtmp or m3u8 external direct link for re-stream on channels.
waiting for your response
goodbye

**Comment by smfils1** [comment]
As of now, video uploads are temporary save locally on your machine and then saved to google drive if you configured your google drive credentials in the server's .env file. To increase the upload limit, look into the VidDropzone.js file. You can edit `maxSize: 25 * 1024 * 1024`.  I will look into your third & fourth request. I anticipate that the go-live feature will be one of the harder ones I have to implement so it will most likely be the last feature I will work on. You are more than welcome to share this repo and contribute.
