### ISSUE TITLE
problem on deploy to heroku

### ISSUE THREAD

**Issue by deeptube** [smfils1/youtube-clone#5]
Hello again Samuel,
I'm trying to deploy using heroku manual deploy from github branch master , but after deploy succed & open run consule from bash & run command npm install & at the time run command npm run dev get error bellow : 

[Imgur](https://i.imgur.com/3mohAk1.png)

& my dyno log on application error is :

`https://gist.github.com/deeptube/e7aa7e1711df522f5789769ede05cb45`

& my env samples is :
client :
```
REACT_APP_BACKEND_PORT=5000 # Port to serve backend (same as in server's PORT .env-sample)
REACT_APP_BACKEND_URL=https://deeptube.herokuapp.com/api  # Ex: http://example.com/api => your production api
```
server :
```
PORT=5000 # Port to serve backend
NODE_ENV=development # OR production
SESSION_DURATION=60 # Number of mins to keep user logged in
MONGODB_URI=mongodb+srv://deeptube:hZE2Z1DI2uqh0Obe@cluster0.nyzou.mongodb.net/Cluster0?retryWrites=true&w=majority # Link From mLab OR MongoDB Atlas to connect to mongoDB
JWT_SECRET=secret2 # Ex: secret2
WEBSITE_URL=https://deeptube.herokuapp.com # Ex: http://example.com => your production website
GOOGLE_CLIENT_ID=181567283099-vr0tfa9o1ck3uhi0fg939c048jmop105.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=FnMsinOMKAvLC25TQFx-1Eif
BACKEND_URL=https://deeptube.herokuapp.com
GOOGLE_DRIVE_CREDENTIALS={"web":{"client_id":"181567283099-vr0tfa9o1ck3uhi0fg939c048jmop105.apps.googleusercontent.com","project_id":"deeptubeio","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"FnMsinOMKAvLC25TQFx-1Eif"}} # Paste the json object all in one line of the generated service account credentials json file: https://dev.to/mornir/create-a-service-account-to-authenticate-with-google-5b1k
```

please make "deploy to heroku" button for easy usage of your fantastic work & if not possible at this time make youtube video about " deploy using Heroku manual deploy from github branch master " to help us.
waiting for your response
finest regards

**Comment by smfils1** [comment]
I will look into making a deploy to heroku button and add better configuration & documentation soon.  As for your application error, make sure you have these Buildpacks on heroku: `heroku/nodejs` & `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git`. Also, make sure you deploy with the same Procfile I have. Please note `npm run dev` is for local development and it assumes that devDependencies were installed which is not the case for heroku. You will need to do npm start which is also defined in the Procfile I mentioned.

These are configurations I have on Heroku but this will change as I document better configurations:
BACKEND_URL => https://yoursite.com/api
REACT_APP_BACKEND_URL => https://yoursite.com/
WEBSITE_URL => same as REACT_APP_BACKEND_URL
GOOGLE_CLIENT_ID, 
GOOGLE_CLIENT_SECRET, 
GOOGLE_DRIVE_CREDENTIALS, 
JWT_SECRET, 
MONGODB_URI,
SESSION_DURATION,

Please note that this project is currently in development and may have some bugs.
Also, be aware of sharing your secrets/credentials as you just did.
